apiVersion: 1

datasources:
  - name: CelestiaOps
    type: postgres
    uid: celestiaops-timescaledb
    url: celestiaops_timescaledb:5432
    user: celestia
    secureJsonData:
      password: celestia
    jsonData:
      database: exoplanets
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: false

  - name: CelestiaOps LAMOST
    type: postgres
    uid: celestiaops-lamost
    url: celestiaops_timescaledb:5432
    user: celestia
    secureJsonData:
      password: celestia
    jsonData:
      database: lamost
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
    isDefault: false
    editable: false
